[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "npm install --legacy-peer-deps"
]

[phases.build]
cmds = [
  "pip install openpyxl qrcode pillow",
  "npm run build"
]

[start]
cmd = "npm start"
